name: Auto Commit and Update Readme

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "Kayden1412"
        git config user.email "toarumajutsu4869@gmail.com"

    - name: Auto Commit
      run: |
        echo "Auto commit message" > temp.txt
        git add temp.txt
        git commit -m "Auto commit"
        git push

    - name: Update Readme
      run: |
        echo "Latest Action Date: $(date)" > readme.md
        git add readme.md
        git commit -m "Update readme with latest action date" || echo "Commit failed"
        git push || echo "Push failed"

    - name: Debugging Info
      run: |
        git status
        git branch -a
        git log -n 5
