name: Hijau

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "Kayden1412"
        git config user.email "${{ secrets.EMAIL }}"

    - name: Update Readme
      run: |
        echo "$(date)" > LAST_UPDATED
        git add LAST_UPDATED
        git commit -m "$(curl -s http://whatthecommit.com/index.txt)" || echo "Commit failed"
        git push || echo "Push failed"

    - name: Debugging Info
      run: |
        git status
        git branch -a
        git log -n 5
